# Generated by Django 3.0.7 on 2021-04-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sightings',
            new_name='Sighting',
        ),
    ]
