# Generated by Django 3.0.7 on 2021-04-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20210411_0524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sighting',
            new_name='Sightings',
        ),
    ]
